title: ben.neise.co.uk
email: ben@neise.co.uk
description: Platform Engineering on Private and Hybrid Clouds.
baseurl: ""
url: "https://ben.neise.co.uk"

timezone: Europe/London
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-paginate
  - jekyll-redirect-from

whitelist:
  - jekyll-redirect-from

show_excerpts: true
excerpt_separator: <!--more-->
disqus:
  shortname: benneise
paginate: 5
include: [".well-known"]
exclude: ["venv-utility"]
github_username: benneise
linkedin_username: benneise

collections:
  guides:
    output: true
