jekyll:
    image: jekyll/jekyll
    environment:
      - JEKYLL_ENV=docker
    command: jekyll serve --watch --drafts --config _config.yml,_config.docker.yml
    ports:
        - 4000:4000
    volumes:
#        - .:/
        - .:/srv/jekyll